spring.application.name=CustomerService
server.port=8080

spring.datasource.url=jdbc:postgresql://ep-round-shadow-b33w1otz-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?
spring.datasource.username=neondb_owner
spring.datasource.password=npg_me3Vtp1WKSUB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.data.redis.host=localhost
spring.data.redis.port=6379

locationiq.api.key=pk.19f1efd1003887a0c6dd0a032c48005d
locationiq.autocomplete.url=https://api.locationiq.com/v1/autocomplete
locationiq.directions.url=https://us1.locationiq.com/v1/directions/driving